import { Exercise, RoutineCollection, WorkoutSession, GymMember, AttendanceRecord } from '../types';
import { withExerciseGuidance } from '../data/exerciseGuidance';
import { EXPANDED_EXERCISES } from '../data/expandedExercises';

export const INITIAL_EXERCISES: Exercise[] = [
  // ==========================================
  // PECTORAL (Chest)
  // ==========================================
  {
    id: 'ex-bench-press',
    name: 'Press de banca (barra)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['antebrazo', 'triceps', 'hombros'],
    equipment: 'barra',
    instructions: 'Acuéstate sobre el banco plano, retrae las escápulas y agarra la barra con una anchura algo mayor que los hombros. Desciende de forma controlada hasta rozar la parte media del pecho y empuja verticalmente.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-pec-deck',
    name: 'Cristos - Mariposa (máquina)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros'],
    equipment: 'maquina',
    instructions: 'Siéntate con la espalda apoyada firmemente y los hombros deprimidos. Cierra los brazos al frente juntando los manerales o coderas sintiendo la máxima contracción esternal.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-incline-bench',
    name: 'Press de banca inclinado (barra)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros', 'triceps'],
    equipment: 'barra',
    instructions: 'Banco inclinado a 30-45 grados. Baja la barra de forma controlada a la porción clavicular del pecho y empuja con potencia sin bloquear los codos bruscamente.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-incline-dumbbell',
    name: 'Press inclinado (mancuernas)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros', 'triceps'],
    equipment: 'mancuerna',
    instructions: 'Press con mancuernas en banco a 30-45 grados para un mayor rango de estiramiento y contracción de la porción clavicular superior del pectoral.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-bench',
    name: 'Press de banca plano (mancuernas)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros', 'triceps'],
    equipment: 'mancuerna',
    instructions: 'Tumbado en banco plano con una mancuerna en cada mano, baja hasta sentir un profundo estiramiento pectoral y empuja en arco convergiendo arriba.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-fly',
    name: 'Aperturas en banco plano (mancuernas)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros'],
    equipment: 'mancuerna',
    instructions: 'Con codos ligeramente semiflexionados, abre los brazos en cruz sintiendo cómo se abren las fibras pectorales y vuelve al centro como abrazando un barril.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-incline-dumbbell-fly',
    name: 'Aperturas inclinadas (mancuernas)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros'],
    equipment: 'mancuerna',
    instructions: 'Banco inclinado a 30 grados. Realiza la apertura enfocando el estiramiento en las fibras superiores del pecho.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-chest-press-machine',
    name: 'Press de pecho sentado (máquina)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['triceps', 'hombros'],
    equipment: 'maquina',
    instructions: 'Ajusta el asiento para que los agarres queden a la altura media del esternón. Empuja manteniendo la espalda pegada al respaldo.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-crossover-high',
    name: 'Cruces de poleas altas',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros'],
    equipment: 'polea',
    instructions: 'Con las poleas en posición alta, da un paso al frente y cruza los manerales hacia abajo y adelante contrayendo la porción inferior del pectoral.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-crossover-low',
    name: 'Cruces de poleas bajas',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros'],
    equipment: 'polea',
    instructions: 'Desde las poleas bajas, eleva las manos hacia arriba y adentro a la altura de la barbilla para enfatizar el haz clavicular superior.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dips-chest',
    name: 'Fondos en paralelas (pectoral)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['triceps', 'hombros'],
    equipment: 'peso_corporal',
    instructions: 'Inclina el torso hacia adelante unos 30 grados con los codos abiertos. Desciende hasta 90 grados y empuja con el pecho.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-pushups',
    name: 'Flexiones de brazos (peso corporal)',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['triceps', 'abdomen'],
    equipment: 'peso_corporal',
    instructions: 'Cuerpo en plancha rígida, manos bajo los hombros. Desciende el pecho hasta rozar el suelo y empuja activando pectoral y core.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-incline-pushups',
    name: 'Flexiones declinadas con pies elevados',
    primaryMuscle: 'pectoral',
    secondaryMuscles: ['hombros', 'triceps'],
    equipment: 'peso_corporal',
    instructions: 'Pies sobre banco o cajón para aumentar la carga sobre las fibras superiores del pecho y hombros.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // DORSALES Y ESPALDA (Lats & Back)
  // ==========================================
  {
    id: 'ex-lat-pulldown',
    name: 'Jalón al pecho (polea)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'antebrazo'],
    equipment: 'polea',
    instructions: 'Agarre amplio prono, tracciona la barra hacia la parte superior del esternón sacando pecho y juntando las escápulas.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-lat-pulldown-neutral',
    name: 'Jalón agarre neutro cerrado (polea)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps'],
    equipment: 'polea',
    instructions: 'Usa agarre V o paralelo. Tira hacia el esternón bajo con codos pegados para enfocar la porción inferior del dorsal.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-pullups',
    name: 'Dominadas pronas (peso corporal)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'antebrazo', 'trapecio'],
    equipment: 'peso_corporal',
    instructions: 'Colgado de la barra con agarre prono amplio, elévate hasta pasar la barbilla por encima de la barra con retracción escapular.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-chinups',
    name: 'Dominadas supinas (peso corporal)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'antebrazo'],
    equipment: 'peso_corporal',
    instructions: 'Agarre supino a la anchura de hombros. Máximo trabajo dorsal y de flexión del codo con implicación de bíceps.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-barbell-row',
    name: 'Remo con barra prono',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['lumbares', 'biceps', 'trapecio'],
    equipment: 'barra',
    instructions: 'Tronco inclinado a 45-60 grados con columna neutra. Lleva la barra hacia el ombligo juntando las escápulas.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-pendlay-row',
    name: 'Remo Pendlay desde el suelo (barra)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['lumbares', 'trapecio'],
    equipment: 'barra',
    instructions: 'Torso estrictamente paralelo al suelo. Cada repetición se arranca en reposo desde los discos en el suelo de forma explosiva.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-row',
    name: 'Remo con mancuerna a una mano (serrucho)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'antebrazo'],
    equipment: 'mancuerna',
    instructions: 'Una rodilla y mano en el banco, espalda recta. Tira de la mancuerna hacia la cadera con el codo pegado al costado.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-incline-dumbbell-row',
    name: 'Remo apoyado en banco inclinado (mancuernas)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['trapecio', 'biceps'],
    equipment: 'mancuerna',
    instructions: 'Pecho apoyado sobre banco a 30-45 grados para aislar los dorsales y romboides sin fatigar la columna lumbar.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-row',
    name: 'Remo Gironda sentado en polea baja',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['trapecio', 'biceps'],
    equipment: 'polea',
    instructions: 'Espalda recta y pecho fuera. Tira del agarre hacia el abdomen bajo manteniendo los codos hacia atrás.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-seated-row-machine',
    name: 'Remo sentado en máquina de placas',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'trapecio'],
    equipment: 'maquina',
    instructions: 'Pecho apoyado en la almohadilla, tracciona los agarres hacia ti concentrándote en el tirón desde los codos.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-t-bar-row',
    name: 'Remo en barra T con apoyo (máquina)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['trapecio', 'biceps'],
    equipment: 'maquina',
    instructions: 'Excelente máquina para trabajar el grosor de la espalda media y dorsal ancho con apoyo esternal ergonómico.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-straight-arm-pulldown',
    name: 'Pullover con brazos rectos en polea',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['triceps'],
    equipment: 'polea',
    instructions: 'De pie con barra recta en polea alta y codos casi bloqueados, empuja la barra hacia los muslos en arco sintiendo el dorsal.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-australian-pullups',
    name: 'Remo invertido en barra baja (peso corporal)',
    primaryMuscle: 'dorsales',
    secondaryMuscles: ['biceps', 'abdomen'],
    equipment: 'peso_corporal',
    instructions: 'Bajo una barra baja a la altura de la cintura, mantén el cuerpo recto como tabla y tira del pecho hacia la barra.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // HOMBROS (Deltoids)
  // ==========================================
  {
    id: 'ex-overhead-press',
    name: 'Press militar (barra)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['triceps', 'trapecio'],
    equipment: 'barra',
    instructions: 'De pie, glúteos y core apretados. Empuja la barra verticalmente por delante de la cara hasta bloquearla sobre la cabeza.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Press de hombros sentado (mancuernas)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['triceps'],
    equipment: 'mancuerna',
    instructions: 'Sentado en banco a 85 grados, empuja las mancuernas desde la altura de las orejas hacia el techo en un movimiento controlado.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-arnold-press',
    name: 'Press Arnold (mancuernas)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['triceps'],
    equipment: 'mancuerna',
    instructions: 'Inicia con palmas hacia el pecho; a medida que empujas hacia arriba rota las muñecas hacia afuera 180 grados.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Elevaciones laterales (mancuernas)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['trapecio'],
    equipment: 'mancuerna',
    instructions: 'Eleva las mancuernas hacia los lados con codos ligeramente flexionados hasta la altura de los hombros sin balancear el cuerpo.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Elevaciones laterales en polea baja',
    primaryMuscle: 'hombros',
    secondaryMuscles: [],
    equipment: 'polea',
    instructions: 'Polea a la altura del tobillo. Tira diagonalmente manteniendo tensión constante durante todo el rango de movimiento.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-front-raise',
    name: 'Elevaciones frontales con mancuernas',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['pectoral'],
    equipment: 'mancuerna',
    instructions: 'Eleva las mancuernas al frente de forma alterna o simultánea hasta la línea de los ojos para activar el deltoides anterior.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-rear-delt-fly',
    name: 'Pájaros / Deltoides posterior (mancuernas)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['trapecio'],
    equipment: 'mancuerna',
    instructions: 'Tronco inclinado hacia adelante a 70 grados. Abre los brazos hacia los laterales apretando la parte posterior del hombro.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-face-pull',
    name: 'Face Pull en polea alta con cuerda',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['trapecio'],
    equipment: 'polea',
    instructions: 'Tracciona la cuerda hacia los ojos separando las manos y rotando los hombros hacia afuera para salud postural y deltoides posterior.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-shoulder-press-machine',
    name: 'Press de hombros en máquina guiada',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['triceps'],
    equipment: 'maquina',
    instructions: 'Siéntate ajustando la altura del asiento para que los agarres queden a nivel de hombros. Empuja de forma uniforme.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-reverse-pec-deck',
    name: 'Pájaros en máquina Peck Deck invertida',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['trapecio'],
    equipment: 'maquina',
    instructions: 'Pecho contra el respaldo de la máquina, abre los brazos hacia atrás aislando con precisión el deltoides posterior.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-upright-row',
    name: 'Remo al mentón (barra)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['trapecio', 'biceps'],
    equipment: 'barra',
    instructions: 'Agarre a la anchura de los hombros. Eleva la barra pegada al cuerpo guiando el movimiento con los codos altos.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-pike-pushups',
    name: 'Flexiones en pica (peso corporal)',
    primaryMuscle: 'hombros',
    secondaryMuscles: ['triceps'],
    equipment: 'peso_corporal',
    instructions: 'Cuerpo en forma de V invertida con cadera alta. Desciende la cabeza hacia el suelo entre las manos y empuja verticalmente.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // BÍCEPS (Biceps & Brachialis)
  // ==========================================
  {
    id: 'ex-biceps-curl-bar',
    name: 'Curl de bíceps (barra recta)',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'barra',
    instructions: 'De pie, con codos fijos a los costados, flexiona los brazos llevando la barra hacia el pecho sin balanceo de cadera.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-ez-bar-curl',
    name: 'Curl de bíceps con barra Z',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'barra',
    instructions: 'El agarre ondulado semiprono reduce la tensión en las muñecas y permite cargar con mayor seguridad y concentración.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-curl',
    name: 'Curl de bíceps alterno con giro (mancuerna)',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'mancuerna',
    instructions: 'Comienza con agarre neutro y supina la muñeca a medida que subes la mancuerna apretando el pico del bíceps arriba.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-biceps-hammer',
    name: 'Curl martillo (mancuernas)',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'mancuerna',
    instructions: 'Agarre neutro con palmas enfrentadas durante todo el movimiento. Gran estímulo para el braquial y braquiorradial.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-biceps-incline',
    name: 'Curl en banco inclinado (mancuernas)',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'mancuerna',
    instructions: 'Banco inclinado a 45 grados. Al colgar los brazos por detrás del torso se logra un máximo estiramiento de la cabeza larga.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-concentration-curl',
    name: 'Curl concentrado a una mano (mancuerna)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Codo apoyado en la cara interna del muslo sentado en el banco. Aisla por completo el bíceps sin posibilidad de inercia.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-preacher-curl-bar',
    name: 'Curl en banco Scott (barra Z)',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'barra',
    instructions: 'Brazos apoyados sobre la almohadilla inclinada. Evita el balanceo y enfoca el esfuerzo en la cabeza corta del bíceps.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-biceps-curl-machine',
    name: 'Curl de bíceps en máquina Scott',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Máquina guiada con curva de resistencia constante ideal para series de congestión y dropsets al fallo.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-biceps-curl',
    name: 'Curl de bíceps en polea baja con barra',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'polea',
    instructions: 'La polea mantiene una tensión milimétrica continua incluso en el punto de máxima contracción en la parte alta.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-hammer-rope',
    name: 'Curl martillo con cuerda en polea baja',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'polea',
    instructions: 'Sujeta los cabos de la cuerda con agarre neutro y flexiona abriendo ligeramente al final del recorrido.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-spider-curl',
    name: 'Spider Curl en banco inclinado (mancuernas)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Pecho apoyado sobre el respaldo inclinado a 45 grados, brazos verticales colgando. Máxima tensión en acortamiento.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // TRÍCEPS (Triceps)
  // ==========================================
  {
    id: 'ex-triceps-pushdown',
    name: 'Extensión de tríceps en polea con cuerda',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['antebrazo'],
    equipment: 'polea',
    instructions: 'Codos pegados a las costillas en polea alta. Extiende los brazos hacia abajo y separa los extremos de la cuerda al final.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-cable-pushdown-straight',
    name: 'Extensión en polea con barra recta',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'polea',
    instructions: 'Agarre prono con barra corta. Permite manejar cargas más pesadas activando la cabeza lateral del tríceps.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-triceps-skullcrusher',
    name: 'Press francés (barra Z)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'barra',
    instructions: 'Tumbado en banco plano, flexiona los codos llevando la barra hacia la coronilla o detrás de la cabeza y extiende con potencia.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-close-grip-bench',
    name: 'Press de banca agarre cerrado (barra)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['pectoral', 'hombros'],
    equipment: 'barra',
    instructions: 'Manos a la anchura de hombros (unos 30-40 cm). Mantén codos pegados al cuerpo para transferir la carga al tríceps.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-triceps-overhead',
    name: 'Extensión sobre la cabeza en polea',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'polea',
    instructions: 'De espaldas a la polea alta o media, extiende los brazos hacia adelante y arriba enfocando la cabeza larga del tríceps.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-overhead-triceps',
    name: 'Extensión sobre la cabeza a dos manos (mancuerna)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Sentado, sujeta una mancuerna pesada con ambas manos por detrás de la nuca y extiéndela verticalmente.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-kickback',
    name: 'Patada de tríceps en banco (mancuerna)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Tronco paralelo al suelo, codo elevado. Extiende el antebrazo hacia atrás aguantando un segundo la contracción.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-triceps-dip-machine',
    name: 'Fondos de tríceps en máquina asistida',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['pectoral', 'hombros'],
    equipment: 'maquina',
    instructions: 'Torso erguido para maximizar la activación del tríceps y reducir el reclutamiento del pectoral.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-bench-dips',
    name: 'Fondos entre bancos (peso corporal)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['hombros'],
    equipment: 'peso_corporal',
    instructions: 'Manos apoyadas al borde de un banco con piernas estiradas. Desciende hasta 90 grados en codos y empuja hacia arriba.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-diamond-pushups',
    name: 'Flexiones diamante (peso corporal)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['pectoral'],
    equipment: 'peso_corporal',
    instructions: 'Junta pulgares e índices bajo el pecho formando un diamante. Desciende y empuja concentrando el esfuerzo en tríceps.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // CUÁDRICEPS (Quadriceps)
  // ==========================================
  {
    id: 'ex-squat',
    name: 'Sentadilla trasera (barra)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'lumbares', 'abdomen'],
    equipment: 'barra',
    instructions: 'Barra sobre los trapecios. Desciende flexionando rodillas y caderas hasta romper el paralelo de 90° con talones bien apoyados.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-front-squat',
    name: 'Sentadilla frontal (barra)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'abdomen'],
    equipment: 'barra',
    instructions: 'Barra apoyada sobre los deltoides frontales con codos altos. Mayor énfasis en cuádriceps y menor sobrecarga lumbar.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-leg-press',
    name: 'Prensa de piernas 45° (máquina)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'pantorrillas'],
    equipment: 'maquina',
    instructions: 'Pies en el centro de la plataforma a la anchura de hombros. Desciende hasta 90 grados y empuja con la planta sin hiperextender rodillas.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-hack-squat',
    name: 'Sentadilla Hack en máquina',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos'],
    equipment: 'maquina',
    instructions: 'Espalda y hombros apoyados en el carro guiado. Permite un recorrido profundo y seguro con máximo foco en el vasto externo.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-leg-extension',
    name: 'Extensiones de cuadríceps en máquina',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Siéntate con la espalda firme. Extiende las piernas contrayendo los cuádriceps y sostén 1 segundo en el pico antes de descender.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-goblet-squat',
    name: 'Sentadilla Goblet (mancuerna)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'abdomen'],
    equipment: 'mancuerna',
    instructions: 'Sujeta una mancuerna pegada al esternón con ambas manos. Desciende verticalmente manteniendo el pecho erguido.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Sentadilla búlgara (mancuernas)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'isquiotibiales'],
    equipment: 'mancuerna',
    instructions: 'Un pie apoyado atrás sobre un banco. Desciende la rodilla trasera hacia el suelo manteniendo la pierna delantera firme.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-walking-lunges',
    name: 'Zancadas caminando con mancuernas',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'pantorrillas'],
    equipment: 'mancuerna',
    instructions: 'Da pasos amplios hacia el frente flexionando ambas rodillas a 90 grados alternando piernas mientras avanzas.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-air-squat',
    name: 'Sentadilla libre profunda (peso corporal)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos'],
    equipment: 'peso_corporal',
    instructions: 'Brazos al frente para equilibrio. Baja profundo con técnica estricta y asciende empujando con talones.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-pistol-squat',
    name: 'Sentadilla pistola a una pierna (peso corporal)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: ['gluteos', 'abdomen'],
    equipment: 'peso_corporal',
    instructions: 'Avanzado: sentadilla a una sola pierna con la pierna contraria estirada al frente sin tocar el suelo.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-sissy-squat',
    name: 'Sentadilla Sissy (peso corporal)',
    primaryMuscle: 'cuadriceps',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    instructions: 'Inclina el torso hacia atrás mientras flexionas las rodillas hacia delante en punteras para un aislamiento extremo del recto femoral.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // ISQUIOTIBIALES / FEMORALES (Hamstrings)
  // ==========================================
  {
    id: 'ex-romanian-deadlift',
    name: 'Peso muerto rumano (barra)',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos', 'lumbares'],
    equipment: 'barra',
    instructions: 'Con ligera flexión de rodillas fija, empuja la cadera hacia atrás bajando la barra por las espinillas hasta sentir estiramiento femoral.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-stiff-leg-deadlift',
    name: 'Peso muerto con piernas semirrígidas (barra)',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos', 'lumbares'],
    equipment: 'barra',
    instructions: 'Rodillas casi rectas pero no bloqueadas. Desciende con la espalda recta para un estiramiento femoral aún más profundo.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-good-mornings',
    name: 'Buenos días con barra',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos', 'lumbares'],
    equipment: 'barra',
    instructions: 'Barra sobre trapecios. Inclina el torso hacia adelante flexionando desde la cadera con la espalda completamente recta.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-rdl',
    name: 'Peso muerto rumano con mancuernas',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos', 'lumbares'],
    equipment: 'mancuerna',
    instructions: 'Desliza las mancuernas por los muslos empujando los glúteos hacia la pared trasera con la espalda plana.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-leg-curl',
    name: 'Curl femoral tumbado en máquina',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['pantorrillas'],
    equipment: 'maquina',
    instructions: 'Tumbado boca abajo, flexiona los talones hacia los glúteos apretando los femorales y desciende en 3 segundos de fase excéntrica.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-seated-leg-curl',
    name: 'Curl femoral sentado en máquina',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'La flexión de cadera al estar sentado coloca los isquiotibiales en una posición de mayor estiramiento y ventaja biomecánica.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-pull-through',
    name: 'Pull-through con cuerda en polea baja',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos'],
    equipment: 'polea',
    instructions: 'De espaldas a la polea baja con la cuerda entre las piernas, haz una bisagra de cadera y extiende con fuerza los glúteos e isquios.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-nordic-curl',
    name: 'Curl nórdico de isquiotibiales (peso corporal)',
    primaryMuscle: 'isquiotibiales',
    secondaryMuscles: ['gluteos'],
    equipment: 'peso_corporal',
    instructions: 'De rodillas con los tobillos anclados, desciende el torso hacia adelante resistiendo la gravedad con los femorales.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // GLÚTEOS (Glutes)
  // ==========================================
  {
    id: 'ex-hip-thrust',
    name: 'Hip Thrust con barra',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['isquiotibiales', 'cuadriceps'],
    equipment: 'barra',
    instructions: 'Espalda superior apoyada en banco, barra acolchada sobre la pelvis. Extiende la cadera bloqueando arriba 2 segundos con retroversión pélvica.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-sumo-deadlift',
    name: 'Peso muerto sumo (barra)',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['isquiotibiales', 'adductores', 'cuadriceps'],
    equipment: 'barra',
    instructions: 'Pies muy separados con punteras hacia afuera. Torso más vertical que en el convencional para enfocar glúteos y aductores.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-hip-thrust',
    name: 'Hip Thrust con mancuerna',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['isquiotibiales'],
    equipment: 'mancuerna',
    instructions: 'Versión cómoda con mancuerna pesada sobre las caderas para repeticiones altas con máxima congestión.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-curtsy-lunge',
    name: 'Zancadas cruzadas de patinador (mancuernas)',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['cuadriceps', 'abductores'],
    equipment: 'mancuerna',
    instructions: 'Da el paso hacia atrás cruzando la pierna en diagonal para activar con gran intensidad el glúteo medio.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-glute-kickback-machine',
    name: 'Patada de glúteos en máquina',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['isquiotibiales'],
    equipment: 'maquina',
    instructions: 'Empuja la plataforma con el talón hacia atrás y arriba concentrando la contracción en el glúteo mayor.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-hip-abductor-machine',
    name: 'Abductores en máquina sentado',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['abductores'],
    equipment: 'maquina',
    instructions: 'Abre las piernas contra las almohadillas sintiendo la quemazón en el glúteo medio y superior.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-cable-glute-kickback',
    name: 'Patada de glúteos con tobillera en polea',
    primaryMuscle: 'gluteos',
    secondaryMuscles: [],
    equipment: 'polea',
    instructions: 'Tobillera en polea baja, patea en arco hacia atrás sin arquear la zona lumbar para aislamiento puro.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-glute-bridge',
    name: 'Puente de glúteos en suelo (peso corporal)',
    primaryMuscle: 'gluteos',
    secondaryMuscles: ['isquiotibiales'],
    equipment: 'peso_corporal',
    instructions: 'Tumbado boca arriba con rodillas flexionadas, eleva la cadera apretando glúteos arriba sin hiperextender la espalda.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-donkey-kicks',
    name: 'Patadas de burro en cuadrupedia (peso corporal)',
    primaryMuscle: 'gluteos',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    instructions: 'En 4 apoyos, eleva la pierna flexionada a 90 grados empujando la planta del pie hacia el techo.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // PANTORRILLAS / GEMELOS (Calves & Soleus)
  // ==========================================
  {
    id: 'ex-calf-raise',
    name: 'Elevación de talones en máquina de pie',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Almohadillas sobre los hombros. Baja los talones al máximo para estirar el gemelo y sube explosivo sobre las punteras.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-seated-calf-machine',
    name: 'Elevación de talones sentado en máquina',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Con rodillas flexionadas a 90 grados, el sóleo asume la mayor parte del trabajo de flexión plantar.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-barbell-calf-raise',
    name: 'Elevación de talones de pie con barra',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'barra',
    instructions: 'Barra sobre trapecios y punteras en un disco o bloque para permitir un recorrido completo en flexión y extensión.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-single-calf',
    name: 'Elevación de talones a una pierna con mancuerna',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Sostén una mancuerna con la mano del lado que trabaja y elévate en la puntera sobre un escalón.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-leg-press-calf',
    name: 'Elevación de talones en prensa 45°',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Punteras apoyadas en el borde inferior de la plataforma de la prensa con rodillas ligeramente desbloqueadas.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-bodyweight-calf',
    name: 'Elevación de talones en escalón (peso corporal)',
    primaryMuscle: 'pantorrillas',
    secondaryMuscles: [],
    equipment: 'peso_corporal',
    instructions: 'Excelente ejercicio para series altas de congestión o recuperación en cualquier lugar.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // ABDOMEN Y CORE (Abdominals & Obliques)
  // ==========================================
  {
    id: 'ex-crunch',
    name: 'Crunch abdominal en polea alta con cuerda',
    primaryMuscle: 'abdomen',
    secondaryMuscles: ['oblicuos'],
    equipment: 'polea',
    instructions: 'De rodillas, sujeta la cuerda detrás de la nuca y enrolla la columna contrayendo los abdominales hacia el suelo.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-hanging-leg-raise',
    name: 'Elevación de piernas colgado en barra',
    primaryMuscle: 'abdomen',
    secondaryMuscles: ['antebrazo', 'oblicuos'],
    equipment: 'peso_corporal',
    instructions: 'Colgado de la barra, eleva las piernas rectas o flexionadas hacia el pecho sin balancear el torso.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-plank',
    name: 'Plancha isométrica en antebrazos',
    primaryMuscle: 'abdomen',
    secondaryMuscles: ['oblicuos', 'lumbares'],
    equipment: 'peso_corporal',
    instructions: 'Cuerpo completamente horizontal en línea recta desde los talones a la cabeza, activando glúteos y transverso.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-ab-roller',
    name: 'Rueda abdominal (Ab Roller)',
    primaryMuscle: 'abdomen',
    secondaryMuscles: ['dorsales', 'hombros'],
    equipment: 'peso_corporal',
    instructions: 'De rodillas, rueda hacia adelante manteniendo la espalda ligeramente redondeada y vuelve contrayendo el core.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-ab-machine',
    name: 'Crunch en máquina de placas',
    primaryMuscle: 'abdomen',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Ajusta la carga y flexiona el torso hacia delante concentrando el trabajo en el recto abdominal.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-side-bend',
    name: 'Inclinaciones laterales con mancuerna',
    primaryMuscle: 'oblicuos',
    secondaryMuscles: ['abdomen'],
    equipment: 'mancuerna',
    instructions: 'Mancuerna en una sola mano, inclina el tronco al lateral y vuelve contrayendo el oblicuo opuesto.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-woodchopper',
    name: 'Leñador en polea (Woodchopper)',
    primaryMuscle: 'oblicuos',
    secondaryMuscles: ['abdomen'],
    equipment: 'polea',
    instructions: 'Gira el torso diagonalmente con los brazos extendidos transfiriendo la potencia desde el core.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-russian-twist',
    name: 'Giros rusos con mancuerna / disco',
    primaryMuscle: 'oblicuos',
    secondaryMuscles: ['abdomen'],
    equipment: 'mancuerna',
    instructions: 'Sentado en el suelo con pies elevados, rota el torso de lado a lado llevando el peso hacia cada cadera.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-bicycle-crunch',
    name: 'Crunch bicicleta para oblicuos (peso corporal)',
    primaryMuscle: 'oblicuos',
    secondaryMuscles: ['abdomen'],
    equipment: 'peso_corporal',
    instructions: 'Lleva el codo hacia la rodilla opuesta mientras estiras la otra pierna de forma rítmica y controlada.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // TRAPECIO Y CUELLO (Trapezius)
  // ==========================================
  {
    id: 'ex-shrugs',
    name: 'Encogimientos con mancuernas pesadas',
    primaryMuscle: 'trapecio',
    secondaryMuscles: ['antebrazo'],
    equipment: 'mancuerna',
    instructions: 'Eleva los hombros en dirección a las orejas contrayendo fuertemente el trapecio superior 2 segundos arriba.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-barbell-shrug',
    name: 'Encogimientos con barra frontal',
    primaryMuscle: 'trapecio',
    secondaryMuscles: ['antebrazo'],
    equipment: 'barra',
    instructions: 'Agarre a la anchura de hombros, sube los hombros verticalmente sin doblar los codos.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-smith-shrug',
    name: 'Encogimientos de trapecio en máquina Smith',
    primaryMuscle: 'trapecio',
    secondaryMuscles: [],
    equipment: 'maquina',
    instructions: 'Barra guiada que permite enfocar todo el esfuerzo en la elevación escapular con máxima sobrecarga.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-cable-shrug',
    name: 'Encogimientos en polea baja con barra',
    primaryMuscle: 'trapecio',
    secondaryMuscles: [],
    equipment: 'polea',
    instructions: 'Tensión constante hacia arriba y adentro siguiendo la línea natural de las fibras del trapecio.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // LUMBARES (Lower Back)
  // ==========================================
  {
    id: 'ex-deadlift',
    name: 'Peso muerto convencional (barra)',
    primaryMuscle: 'lumbares',
    secondaryMuscles: ['isquiotibiales', 'gluteos', 'trapecio', 'antebrazo'],
    equipment: 'barra',
    instructions: 'Pies bajo la barra a la anchura de las caderas. Empuja el suelo con las piernas extendiendo caderas y rodillas al unísono.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-hyperextensions',
    name: 'Hiperextensiones en banco 45°',
    primaryMuscle: 'lumbares',
    secondaryMuscles: ['gluteos', 'isquiotibiales'],
    equipment: 'peso_corporal',
    instructions: 'Flexiona y extiende el torso controladamente fortaleciendo los erectores espinales y cadena posterior.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-superman',
    name: 'Superman en suelo (peso corporal)',
    primaryMuscle: 'lumbares',
    secondaryMuscles: ['gluteos'],
    equipment: 'peso_corporal',
    instructions: 'Tumbado boca abajo, eleva simultáneamente brazos y piernas despegándolos del suelo durante 3 segundos.',
    isFavorite: false,
    isCustom: false,
  },

  // ==========================================
  // ANTEBRAZO Y AGARRE (Forearms & Grip)
  // ==========================================
  {
    id: 'ex-wrist-curl',
    name: 'Curl de muñeca en banco (barra)',
    primaryMuscle: 'antebrazo',
    secondaryMuscles: [],
    equipment: 'barra',
    instructions: 'Antebrazos sobre el banco con palmas arriba, flexiona las muñecas subiendo la barra para hipertrofiar los flexores.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-reverse-wrist-curl',
    name: 'Curl de muñeca invertido (barra)',
    primaryMuscle: 'antebrazo',
    secondaryMuscles: [],
    equipment: 'barra',
    instructions: 'Palmas hacia abajo, extiende las muñecas hacia arriba para fortalecer los extensores del antebrazo.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-wrist-curl',
    name: 'Curl de muñeca con mancuerna',
    primaryMuscle: 'antebrazo',
    secondaryMuscles: [],
    equipment: 'mancuerna',
    instructions: 'Trabajo unilateral para corregir desequilibrios de fuerza y masa en los antebrazos.',
    isFavorite: false,
    isCustom: false,
  },
  {
    id: 'ex-farmers-walk',
    name: 'Paseo del granjero con mancuernas pesadas',
    primaryMuscle: 'antebrazo',
    secondaryMuscles: ['trapecio', 'abdomen'],
    equipment: 'mancuerna',
    instructions: 'Camina erguido sosteniendo mancuernas muy pesadas a los lados desafiando la fuerza de agarre y trapecios.',
    isFavorite: true,
    isCustom: false,
  },
  {
    id: 'ex-dead-hang',
    name: 'Suspensión pasiva colgado en barra (peso corporal)',
    primaryMuscle: 'antebrazo',
    secondaryMuscles: ['dorsales', 'hombros'],
    equipment: 'peso_corporal',
    instructions: 'Cuélgate de la barra de dominadas con agarre prono aguantando por tiempo para desarrollar fuerza de agarre descomunal.',
    isFavorite: false,
    isCustom: false,
  },
  ...EXPANDED_EXERCISES,
].map((exercise) => withExerciseGuidance(exercise as Exercise));

export const INITIAL_COLLECTION: RoutineCollection = {
  id: 'col-brazos-fuertes',
  title: 'Brazos Fuertes y Torneados',
  subtitle: 'Plan de hipertrofia y definición',
  days: [
    {
      id: 'day-1',
      name: 'Día 1 - Bíceps y Tríceps',
      dayBadge: 'lun',
      estimatedMinutes: 45,
      estimatedCalories: 412,
      exercisesCount: 4,
      exercises: [
        {
          id: 'day-1-re-1',
          routineId: 'day-1',
          exerciseId: 'ex-biceps-curl-bar',
          orderIndex: 1,
          targetSets: 4,
          targetRepRange: '12-15',
          targetWeightRange: '30-40',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 30, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 15, weightKg: 35, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 40, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 40, isCompleted: false },
          ],
        },
        {
          id: 'day-1-re-2',
          routineId: 'day-1',
          exerciseId: 'ex-triceps-pushdown',
          orderIndex: 2,
          targetSets: 4,
          targetRepRange: '12-15',
          targetWeightRange: '35-45',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 35, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 15, weightKg: 40, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 45, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 12, weightKg: 45, isCompleted: false },
          ],
        },
        {
          id: 'day-1-re-3',
          routineId: 'day-1',
          exerciseId: 'ex-biceps-hammer',
          orderIndex: 3,
          targetSets: 3,
          targetRepRange: '10-12',
          targetWeightRange: '14-18',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 14, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 16, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 18, isCompleted: false },
          ],
        },
        {
          id: 'day-1-re-4',
          routineId: 'day-1',
          exerciseId: 'ex-triceps-skullcrusher',
          orderIndex: 4,
          targetSets: 3,
          targetRepRange: '10-12',
          targetWeightRange: '25-35',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 25, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 30, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 35, isCompleted: false },
          ],
        },
      ],
    },
    {
      id: 'day-2',
      name: 'Día 2 - Pecho, Hombros y Abdomen',
      dayBadge: 'mar',
      estimatedMinutes: 73,
      estimatedCalories: 763,
      exercisesCount: 5,
      exercises: [
        {
          id: 'day-2-re-1',
          routineId: 'day-2',
          exerciseId: 'ex-bench-press',
          orderIndex: 1,
          targetSets: 4,
          targetRepRange: '12-15',
          targetWeightRange: '40-55',
          targetRestSeconds: 90,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 40, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 15, weightKg: 45, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 50, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 55, isCompleted: false },
          ],
        },
        {
          id: 'day-2-re-2',
          routineId: 'day-2',
          exerciseId: 'ex-pec-deck',
          orderIndex: 2,
          targetSets: 4,
          targetRepRange: '10-15',
          targetWeightRange: '60-75',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 60, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 65, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 70, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 75, isCompleted: false },
          ],
        },
        {
          id: 'day-2-re-3',
          routineId: 'day-2',
          exerciseId: 'ex-incline-bench',
          orderIndex: 3,
          targetSets: 4,
          targetRepRange: '10-15',
          targetWeightRange: '40-55',
          targetRestSeconds: 90,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 40, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 45, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 50, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 55, isCompleted: false },
          ],
        },
        {
          id: 'day-2-re-4',
          routineId: 'day-2',
          exerciseId: 'ex-lateral-raise',
          orderIndex: 4,
          targetSets: 4,
          targetRepRange: '12-15',
          targetWeightRange: '10-14',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 10, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 15, weightKg: 10, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 12, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 12, weightKg: 14, isCompleted: false },
          ],
        },
        {
          id: 'day-2-re-5',
          routineId: 'day-2',
          exerciseId: 'ex-crunch',
          orderIndex: 5,
          targetSets: 4,
          targetRepRange: '15-20',
          targetWeightRange: '35-45',
          targetRestSeconds: 45,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 20, weightKg: 35, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 20, weightKg: 40, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 15, weightKg: 45, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 15, weightKg: 45, isCompleted: false },
          ],
        },
      ],
    },
    {
      id: 'day-3',
      name: 'Día 3 - Espalda, Lumbares y Pantorrillas',
      dayBadge: 'mie',
      estimatedMinutes: 51,
      estimatedCalories: 537,
      exercisesCount: 4,
      exercises: [
        {
          id: 'day-3-re-1',
          routineId: 'day-3',
          exerciseId: 'ex-lat-pulldown',
          orderIndex: 1,
          targetSets: 4,
          targetRepRange: '10-12',
          targetWeightRange: '55-70',
          targetRestSeconds: 75,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 55, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 60, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 65, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 70, isCompleted: false },
          ],
        },
        {
          id: 'day-3-re-2',
          routineId: 'day-3',
          exerciseId: 'ex-barbell-row',
          orderIndex: 2,
          targetSets: 4,
          targetRepRange: '8-12',
          targetWeightRange: '50-65',
          targetRestSeconds: 90,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 50, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 55, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 60, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 8, weightKg: 65, isCompleted: false },
          ],
        },
        {
          id: 'day-3-re-3',
          routineId: 'day-3',
          exerciseId: 'ex-deadlift',
          orderIndex: 3,
          targetSets: 3,
          targetRepRange: '6-8',
          targetWeightRange: '80-110',
          targetRestSeconds: 120,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 8, weightKg: 80, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 8, weightKg: 95, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 6, weightKg: 110, isCompleted: false },
          ],
        },
        {
          id: 'day-3-re-4',
          routineId: 'day-3',
          exerciseId: 'ex-calf-raise',
          orderIndex: 4,
          targetSets: 4,
          targetRepRange: '15-20',
          targetWeightRange: '40-60',
          targetRestSeconds: 45,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 20, weightKg: 40, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 20, weightKg: 50, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 15, weightKg: 55, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 15, weightKg: 60, isCompleted: false },
          ],
        },
      ],
    },
    {
      id: 'day-4',
      name: 'Día 4 - Bíceps y Tríceps',
      dayBadge: 'jue',
      estimatedMinutes: 36,
      estimatedCalories: 333,
      exercisesCount: 3,
      exercises: [
        {
          id: 'day-4-re-1',
          routineId: 'day-4',
          exerciseId: 'ex-biceps-curl-bar',
          orderIndex: 1,
          targetSets: 4,
          targetRepRange: '10-12',
          targetWeightRange: '35-45',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 35, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 40, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 45, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 45, isCompleted: false },
          ],
        },
        {
          id: 'day-4-re-2',
          routineId: 'day-4',
          exerciseId: 'ex-triceps-pushdown',
          orderIndex: 2,
          targetSets: 4,
          targetRepRange: '12-15',
          targetWeightRange: '40-50',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 40, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 45, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 50, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 50, isCompleted: false },
          ],
        },
        {
          id: 'day-4-re-3',
          routineId: 'day-4',
          exerciseId: 'ex-biceps-hammer',
          orderIndex: 3,
          targetSets: 3,
          targetRepRange: '12-15',
          targetWeightRange: '12-16',
          targetRestSeconds: 60,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 12, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 14, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 16, isCompleted: false },
          ],
        },
      ],
    },
    {
      id: 'day-5',
      name: 'Día 5 - Piernas, Glúteos y Pantorrillas',
      dayBadge: 'vie',
      estimatedMinutes: 54,
      estimatedCalories: 603,
      exercisesCount: 4,
      exercises: [
        {
          id: 'day-5-re-1',
          routineId: 'day-5',
          exerciseId: 'ex-squat',
          orderIndex: 1,
          targetSets: 4,
          targetRepRange: '8-10',
          targetWeightRange: '70-95',
          targetRestSeconds: 120,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 10, weightKg: 70, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 80, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 8, weightKg: 90, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 8, weightKg: 95, isCompleted: false },
          ],
        },
        {
          id: 'day-5-re-2',
          routineId: 'day-5',
          exerciseId: 'ex-leg-press',
          orderIndex: 2,
          targetSets: 4,
          targetRepRange: '10-12',
          targetWeightRange: '120-160',
          targetRestSeconds: 90,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 120, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 140, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 150, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 160, isCompleted: false },
          ],
        },
        {
          id: 'day-5-re-3',
          routineId: 'day-5',
          exerciseId: 'ex-romanian-deadlift',
          orderIndex: 3,
          targetSets: 4,
          targetRepRange: '10-12',
          targetWeightRange: '60-80',
          targetRestSeconds: 90,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 60, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 70, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 75, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 80, isCompleted: false },
          ],
        },
        {
          id: 'day-5-re-4',
          routineId: 'day-5',
          exerciseId: 'ex-calf-raise',
          orderIndex: 4,
          targetSets: 4,
          targetRepRange: '15-20',
          targetWeightRange: '50-70',
          targetRestSeconds: 45,
          defaultSets: [
            { id: 's1', setNumber: 1, type: 'normal', reps: 20, weightKg: 50, isCompleted: false },
            { id: 's2', setNumber: 2, type: 'normal', reps: 20, weightKg: 60, isCompleted: false },
            { id: 's3', setNumber: 3, type: 'normal', reps: 15, weightKg: 65, isCompleted: false },
            { id: 's4', setNumber: 4, type: 'normal', reps: 15, weightKg: 70, isCompleted: false },
          ],
        },
      ],
    },
  ],
};

export const INITIAL_WORKOUT_HISTORY: WorkoutSession[] = [
  {
    id: 'sample-workout-1',
    routineId: 'day-2',
    name: 'Pecho, Hombros y Abdomen',
    startTime: new Date(Date.now() - 2 * 86400000).toISOString(),
    endTime: new Date(Date.now() - 2 * 86400000 + 4380000).toISOString(),
    durationSeconds: 4380,
    totalKcal: 763,
    totalVolumeKg: 1250,
    exercises: [
      {
        id: 'sw1-e1',
        workoutId: 'sample-workout-1',
        exerciseId: 'ex-bench-press',
        exerciseName: 'Press de banca (barra)',
        primaryMuscle: 'pectoral',
        orderIndex: 1,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 40, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 45, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 50, isCompleted: true },
          { id: 's4', setNumber: 4, type: 'normal', reps: 8, weightKg: 55, isCompleted: true },
        ],
      },
      {
        id: 'sw1-e2',
        workoutId: 'sample-workout-1',
        exerciseId: 'ex-incline-bench',
        exerciseName: 'Press de banca inclinado (barra)',
        primaryMuscle: 'pectoral',
        orderIndex: 2,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 40, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 45, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 8, weightKg: 50, isCompleted: true },
        ],
      },
      {
        id: 'sw1-e3',
        workoutId: 'sample-workout-1',
        exerciseId: 'ex-lateral-raise',
        exerciseName: 'Elevaciones laterales (mancuernas)',
        primaryMuscle: 'hombros',
        orderIndex: 3,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 10, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 12, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 12, weightKg: 12, isCompleted: true },
          { id: 's4', setNumber: 4, type: 'normal', reps: 10, weightKg: 14, isCompleted: true },
        ],
      },
      {
        id: 'sw1-e4',
        workoutId: 'sample-workout-1',
        exerciseId: 'ex-crunch',
        exerciseName: 'Crunch abdominal en polea',
        primaryMuscle: 'abdomen',
        orderIndex: 4,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 20, weightKg: 35, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 15, weightKg: 40, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 15, weightKg: 45, isCompleted: true },
        ],
      },
    ],
    isCompleted: true,
  },
  {
    id: 'sample-workout-2',
    routineId: 'day-1',
    name: 'Bíceps y Tríceps',
    startTime: new Date(Date.now() - 1 * 86400000).toISOString(),
    endTime: new Date(Date.now() - 1 * 86400000 + 2700000).toISOString(),
    durationSeconds: 2700,
    totalKcal: 412,
    totalVolumeKg: 1150,
    exercises: [
      {
        id: 'sw2-e1',
        workoutId: 'sample-workout-2',
        exerciseId: 'ex-biceps-curl-bar',
        exerciseName: 'Curl de bíceps (barra)',
        primaryMuscle: 'biceps',
        orderIndex: 1,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 30, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 35, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 40, isCompleted: true },
          { id: 's4', setNumber: 4, type: 'normal', reps: 8, weightKg: 40, isCompleted: true },
        ],
      },
      {
        id: 'sw2-e2',
        workoutId: 'sample-workout-2',
        exerciseId: 'ex-triceps-pushdown',
        exerciseName: 'Extensión de tríceps en polea',
        primaryMuscle: 'triceps',
        orderIndex: 2,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 15, weightKg: 35, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 12, weightKg: 40, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 45, isCompleted: true },
        ],
      },
      {
        id: 'sw2-e3',
        workoutId: 'sample-workout-2',
        exerciseId: 'ex-biceps-hammer',
        exerciseName: 'Curl martillo (mancuernas)',
        primaryMuscle: 'biceps',
        orderIndex: 3,
        sets: [
          { id: 's1', setNumber: 1, type: 'normal', reps: 12, weightKg: 14, isCompleted: true },
          { id: 's2', setNumber: 2, type: 'normal', reps: 10, weightKg: 16, isCompleted: true },
          { id: 's3', setNumber: 3, type: 'normal', reps: 10, weightKg: 16, isCompleted: true },
        ],
      },
    ],
    isCompleted: true,
  },
];

export const INITIAL_BODY_MEASUREMENTS = [
  {
    id: 'bm-1',
    date: new Date(Date.now() - 28 * 86400000).toISOString(),
    weightKg: 78.5,
    bodyFatPct: 15.2,
    chestCm: 102.0,
    armLeftCm: 37.0,
    armRightCm: 37.5,
    waistCm: 84.0,
    hipsCm: 99.0,
    thighLeftCm: 58.0,
    thighRightCm: 58.5,
    calfCm: 37.0,
    shouldersCm: 118.0,
    notes: 'Inicio de mesociclo de volumen.',
  },
  {
    id: 'bm-2',
    date: new Date(Date.now() - 14 * 86400000).toISOString(),
    weightKg: 79.3,
    bodyFatPct: 15.0,
    chestCm: 103.0,
    armLeftCm: 37.5,
    armRightCm: 38.0,
    waistCm: 83.5,
    hipsCm: 99.5,
    thighLeftCm: 58.5,
    thighRightCm: 59.0,
    calfCm: 37.5,
    shouldersCm: 119.0,
    notes: 'Buena progresión en brazos y pecho.',
  },
  {
    id: 'bm-3',
    date: new Date(Date.now() - 1 * 86400000).toISOString(),
    weightKg: 80.2,
    bodyFatPct: 14.8,
    chestCm: 104.5,
    armLeftCm: 38.2,
    armRightCm: 38.8,
    waistCm: 83.0,
    hipsCm: 100.0,
    thighLeftCm: 59.5,
    thighRightCm: 60.0,
    calfCm: 38.0,
    shouldersCm: 120.5,
    notes: 'Aumento limpio de masa muscular.',
  },
];

export const INITIAL_GYM_MEMBERS = [
  {
    id: 'mem-1',
    fullName: 'Alejandro Ramos',
    email: 'alejandro.ramos@email.com',
    phone: '+34 612 345 678',
    membershipNumber: 'SOC-001',
    enrollmentDate: new Date(Date.now() - 90 * 86400000).toISOString(),
    status: 'activo' as const,
    objective: 'hipertrofia' as const,
    level: 'intermedio' as const,
    assignedRoutineId: 'col-brazos-fuertes',
    assignedRoutineTitle: 'Brazos Fuertes y Torneados',
    lastWorkoutDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    completedWorkoutsCount: 38,
    currentWeightKg: 80.2,
  },
  {
    id: 'mem-2',
    fullName: 'Beatriz Morales',
    email: 'beatriz.m@email.com',
    phone: '+34 622 987 654',
    membershipNumber: 'SOC-002',
    enrollmentDate: new Date(Date.now() - 60 * 86400000).toISOString(),
    status: 'activo' as const,
    objective: 'perdida_grasa' as const,
    level: 'principiante' as const,
    assignedRoutineId: 'col-brazos-fuertes',
    assignedRoutineTitle: 'Brazos Fuertes y Torneados',
    lastWorkoutDate: new Date(Date.now() - 2 * 86400000).toISOString(),
    completedWorkoutsCount: 22,
    currentWeightKg: 64.5,
  },
  {
    id: 'mem-3',
    fullName: 'Carlos Santana',
    email: 'carlos.santana@email.com',
    phone: '+34 633 456 789',
    membershipNumber: 'SOC-003',
    enrollmentDate: new Date(Date.now() - 45 * 86400000).toISOString(),
    status: 'activo' as const,
    objective: 'fuerza' as const,
    level: 'avanzado' as const,
    assignedRoutineId: 'col-brazos-fuertes',
    assignedRoutineTitle: 'Brazos Fuertes y Torneados',
    lastWorkoutDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    completedWorkoutsCount: 29,
    currentWeightKg: 88.0,
  },
  {
    id: 'mem-4',
    fullName: 'Diana Navarro',
    email: 'diana.n@email.com',
    phone: '+34 644 112 233',
    membershipNumber: 'SOC-004',
    enrollmentDate: new Date(Date.now() - 30 * 86400000).toISOString(),
    status: 'activo' as const,
    objective: 'hipertrofia' as const,
    level: 'intermedio' as const,
    assignedRoutineId: 'col-brazos-fuertes',
    assignedRoutineTitle: 'Brazos Fuertes y Torneados',
    lastWorkoutDate: new Date(Date.now() - 3 * 86400000).toISOString(),
    completedWorkoutsCount: 14,
    currentWeightKg: 58.2,
  },
  {
    id: 'mem-5',
    fullName: 'Enrique Gallego',
    email: 'enrique.gallego@email.com',
    phone: '+34 655 334 455',
    membershipNumber: 'SOC-005',
    enrollmentDate: new Date(Date.now() - 120 * 86400000).toISOString(),
    status: 'inactivo' as const,
    objective: 'salud_general' as const,
    level: 'principiante' as const,
    lastWorkoutDate: new Date(Date.now() - 25 * 86400000).toISOString(),
    completedWorkoutsCount: 19,
    currentWeightKg: 76.0,
  },
  {
    id: 'mem-6',
    fullName: 'Fabiola Ruiz',
    email: 'fabiola.ruiz@email.com',
    phone: '+34 666 778 899',
    membershipNumber: 'SOC-006',
    enrollmentDate: new Date(Date.now() - 5 * 86400000).toISOString(),
    status: 'pendiente' as const,
    objective: 'hipertrofia' as const,
    level: 'principiante' as const,
    completedWorkoutsCount: 1,
    currentWeightKg: 61.0,
  },
];

export const INITIAL_ATTENDANCE_LOGS: AttendanceRecord[] = [
  {
    id: 'att-1',
    memberId: 'mem-1',
    memberName: 'Alejandro Ramos',
    membershipNumber: 'SOC-001',
    timestamp: new Date(Date.now() - 35 * 60000).toISOString(),
    type: 'entrada',
  },
  {
    id: 'att-2',
    memberId: 'mem-3',
    memberName: 'Carlos Santana',
    membershipNumber: 'SOC-003',
    timestamp: new Date(Date.now() - 50 * 60000).toISOString(),
    type: 'entrada',
  },
  {
    id: 'att-3',
    memberId: 'mem-4',
    memberName: 'Diana Navarro',
    membershipNumber: 'SOC-004',
    timestamp: new Date(Date.now() - 75 * 60000).toISOString(),
    type: 'entrada',
  },
  {
    id: 'att-4',
    memberId: 'mem-2',
    memberName: 'Beatriz Morales',
    membershipNumber: 'SOC-002',
    timestamp: new Date(Date.now() - 110 * 60000).toISOString(),
    type: 'entrada',
  },
  {
    id: 'att-5',
    memberId: 'mem-2',
    memberName: 'Beatriz Morales',
    membershipNumber: 'SOC-002',
    timestamp: new Date(Date.now() - 25 * 60000).toISOString(),
    type: 'salida',
  },
];
